name: Maven package publish and Docker image publish

on:
  push:
    branches:
    - 'ci/*'
    - main
    
jobs:
  maven:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        cache: 'maven'

    - name: Maven cpv
      run: mvn clean package verify
      
    - name: Upload artifact for Docker job
      uses: actions/upload-artifact@v4
      with:
        name: java-app
        path: '${{ github.workspace }}/target/*.jar'

  docker:

    runs-on: ubuntu-latest
    needs: maven
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4
    - name: Download artifact from Maven job
      uses: actions/download-artifact@v4
      with:
        name: java-app
    - name: Logging in to Docker
      run: docker login ghcr.io -u redwing71 -p ${{ github.token }}
    - name: Build the Docker image
      run: docker build . -t ghcr.io/redwing71/cubix/1/optional/app:springboot
    - name: Publishing the Docker image
      run: docker push ghcr.io/redwing71/cubix/1/optional/app:springboot

      